export const GENRE_LIST_REQUEST = 'GENRE_LIST_REQUEST';
export const GENRE_LIST_SUCCESS = 'GENRE_LIST_SUCCESS';
export const GENRE_LIST_FAIL = 'GENRE_LIST_FAIL';

export const GENRE_ADD_REQUEST = 'GENRE_ADD_REQUEST';
export const GENRE_ADD_SUCCESS = 'GENRE_ADD_SUCCESS';
export const GENRE_ADD_FAIL = 'GENRE_ADD_FAIL';