export const MOVIE_LIST_REQUEST = 'MOVIE_LIST_REQUEST';
export const MOVIE_LIST_SUCCESS = 'MOVIE_LIST_SUCCESS';
export const MOVIE_LIST_FAIL = 'MOVIE_LIST_FAIL';

export const MOVIE_DETAILS_REQUEST = 'MOVIE_DETAILS_REQUEST';
export const MOVIE_DETAILS_SUCCESS = 'MOVIE_DETAILS_SUCCESS';
export const MOVIE_DETAILS_FAIL = 'MOVIE_DETAILS_FAIL';

export const MOVIE_TOPRATED_DETAILS_REQUEST = 'MOVIE_TOPRATED_DETAILS_REQUEST';
export const MOVIE_TOPRATED_DETAILS_SUCCESS = 'MOVIE_TOPRATED_DETAILS_SUCCESS';
export const MOVIE_TOPRATED_DETAILS_FAIL = 'MOVIE_TOPRATED_DETAILS_FAIL';

export const MOVIE_NAME_SEARCH_REQUEST = 'MOVIE_NAME_SEARCH_REQUEST';
export const MOVIE_NAME_SEARCH_SUCCESS = 'MOVIE_NAME_SEARCH_SUCCESS';
export const MOVIE_NAME_SEARCH_FAIL = 'MOVIE_NAME_SEARCH_FAIL';

export const MOVIE_GENRE_SEARCH_REQUEST = 'MOVIE_GENRE_SEARCH_REQUEST';
export const MOVIE_GENRE_SEARCH_SUCCESS = 'MOVIE_GENRE_SEARCH_SUCCESS';
export const MOVIE_GENRE_SEARCH_FAIL = 'MOVIE_GENRE_SEARCH_FAIL';

export const MOVIE_CREATE_REQUEST = 'MOVIE_CREATE_REQUEST';
export const MOVIE_CREATE_SUCCESS = 'MOVIE_CREATE_SUCCESS';
export const MOVIE_CREATE_FAIL = 'MOVIE_CREATE_FAIL';

export const MOVIE_COMMENT_REQUEST = 'MOVIE_COMMENT_REQUEST';
export const MOVIE_COMMENT_SUCCESS = 'MOVIE_COMMENT_SUCCESS';
export const MOVIE_COMMENT_FAIL = 'MOVIE_COMMENT_FAIL';

export const MOVIE_RATE_REQUEST = 'MOVIE_RATE_REQUEST';
export const MOVIE_RATE_SUCCESS = 'MOVIE_RATE_SUCCESS';
export const MOVIE_RATE_FAIL = 'MOVIE_RATE_FAIL';

export const MOVIE_DELETE_REQUEST = 'MOVIE_DELETE_REQUEST';
export const MOVIE_DELETE_SUCCESS = 'MOVIE_DELETE_SUCCESS';
export const MOVIE_DELETE_FAIL = 'MOVIE_DELETE_FAIL';

export const MOVIE_UPDATE_REQUEST = 'MOVIE_UPDATE_REQUEST';
export const MOVIE_UPDATE_SUCCESS = 'MOVIE_UPDATE_SUCCESS';
export const MOVIE_UPDATE_FAIL = 'MOVIE_UPDATE_FAIL';
export const MOVIE_UPDATE_RESET = 'MOVIE_UPDATE_RESET';
